### ISSUE TITLE
Cannot build because of error XLS0503

### ISSUE THREAD

**Issue by effpath999** [Microsoft/TailwindTraders-Mobile#5]
Hello, when I try to build TailwindTraders.Mobile solution I receive a few times error XLS0503: A value of type 'MenuItem' cannot be added to a collection or dictionary of type 'ShellItemCollection', and XLS0503: A value of type 'ShellContent' cannot be added to a collection or dictionary of type 'ShellSectionCollection'.
I tried to build in Visual Studio 2017 15.9.3 and Visual Studio 2019 Preview.

**Comment by MarcosCobena** [comment]
Hi @effpath999,

I'm an every day Visual Studio for Mac user and haven't seen that error before. However, seeing build outputs today I've noticed there's a Xamarin.Forms 4.0 NuGet pre-release which's no longer found and thus restoring a different one.

May this be your issue, would it be possible you try again? If keeps failing, could you please share which NuGets are you restoring?

Thanks,

-Marcos

**Comment by MarcosCobena** [comment]
Let me please close this issue for now, feel free to reopen it if may be needed again.

**Comment by a-einstein** [comment]
This problem still is around.
I am using Gastropod. So far that has been the only example I got working at all. 
I only succeeded on an emulator for Oreo. 
I have also updated Xamarin.Forms to 4.0.0.169046-pre5. No better luck.

It is all quite confusing and slow. At several builds Visual Studio seemed to get stranded with this error message. But the build does not stop, and does not seem to really do something either. Interrupting the build or even quitting Visual Studio does not work. The only option left is killing it.

I was also trying on Lollipop. When I do not get deployment errors, it crashes on "Java.Lang.NoSuchMethodError". Apparently It also needs some higher Android version.

**Comment by DualOpAmp** [comment]
This is still an issue for me. Even after downloading the Microsoft Shell Introduction https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals/
I get this error.

**Comment by pulimento** [comment]
I'm sorry to hear that. I think that error is related to some code already cached. Please, can you update your Visual Studio, the Xamarin Forms packages (now 4.0 is stable), and check out this project in another different location? Thanks in advance :)
